// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

uint16 constant PARAM_TYPE1_DEFAULT_AML_RULE = 4;
uint16 constant PARAM_TYPE1_DEFAULT_KYC_RULE = 5;
uint16 constant PARAM_TYPE1_DEFAULT_KYCAML_RULE = 6;

uint16 constant PARAM_TYPE2_DEFAULT_AML_RULE = 24;
uint16 constant PARAM_TYPE2_DEFAULT_KYC_RULE = 25;
uint16 constant PARAM_TYPE2_DEFAULT_KYCAML_RULE = 26;

uint16 constant PARAM_TYPE3_DEFAULT_AML_RULE = 34;
uint16 constant PARAM_TYPE3_DEFAULT_KYC_RULE = 35;
uint16 constant PARAM_TYPE3_DEFAULT_KYCAML_RULE = 36;

